.TH "FunctionJumper Directory Reference" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionJumper Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEventInterface\&.cs\fP"
.br
.RI "\fIAn interface to the events (which you cann't see without reflection!) \fP"
.ti -1c
.RI "file \fBEventMaster\&.cs\fP"
.br
.RI "\fICompiles, maintains and activates events\&. \fP"
.ti -1c
.RI "file \fBReturnCodes\&.cs\fP"
.br
.RI "\fIAll the return codes used by FunctionJumper! \fP"
.in -1c
