.TH "FunctionJumper/EventInterface.cs" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionJumper/EventInterface.cs \- An interface to the events (which you cann't see without reflection!)  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunctionJumper\&.EventInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.in -1c
.SH "Detailed Description"
.PP 
An interface to the events (which you cann't see without reflection!) 

This file contains the EventInterface\&. This is where you subscrie and unsuscribe to your events\&. Accsessed through \fBFunctionJumper\&.EventMaster\fP's getEvent function\&.
.PP
\fBTodo\fP
.RS 4
Omptimize code
.RE
.PP

.PP
Definition in file \fBEventInterface\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Function Jumper from the source code\&.
