.TH "FunctionJumper/EventMaster.cs" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionJumper/EventMaster.cs \- Compiles, maintains and activates events\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunctionJumper\&.EventMaster\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.in -1c
.SH "Detailed Description"
.PP 
Compiles, maintains and activates events\&. 

This file contains the EventMaster\&. This is where you compile newevent systems, set them up and accses previously made ones\&. You'll need to use \fBFunctionJumper\&.EventInterface\fP to subscribe to those events\&.
.PP
\fBTodo\fP
.RS 4
Omptimize code 
.PP
Make this progam NOT classified as a virus 
.PP
Remove need for a C# compiler installed 
.PP
Fix (un?)common stack trace issues 
.PP
Implement Linux suport 
.PP
Implement error handling
.RE
.PP
.PP
\fBBug\fP
.RS 4
VS2015 crashes from 'Step Into' on an overriden function 
.PP
No/Buggy support for instance functions
.RE
.PP

.PP
Definition in file \fBEventMaster\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Function Jumper from the source code\&.
