.TH "FunctionJumper.EventInterface" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionJumper.EventInterface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBAddSub\fP (MethodInfo newSub)"
.br
.ti -1c
.RI "int \fBRemoveSub\fP (MethodInfo oldSub)"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "int \fBInitINTERNAL\fP (MethodInfo sourceMethod, Type _funcType, MethodInfo _delegateMethod, string _funcName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MethodInfo \fBeventSub\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "MethodInfo \fBeventUnSub\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "string \fBfuncName\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "Type \fBfuncType\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "MethodInfo \fBdelegateMethod\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "Type \fBdelegateType\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "int \fBsubCount\fP\fC [get, private set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file EventInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Function Jumper from the source code\&.
