.TH "FunctionJumper/ReturnCodes.cs" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionJumper/ReturnCodes.cs \- All the return codes used by FunctionJumper!  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFunctionJumper\&.ReturnCodes\fP { \fBFunctionJumper\&.ReturnCodes\&.Success\fP, \fBFunctionJumper\&.ReturnCodes\&.NoSubOrUnSubWasMade\fP, \fBFunctionJumper\&.ReturnCodes\&.NeedAlteastOneSub\fP, \fBFunctionJumper\&.ReturnCodes\&.NoSub\fP, \fBFunctionJumper\&.ReturnCodes\&.NoMethodInfo\fP, \fBFunctionJumper\&.ReturnCodes\&.NoEvent\fP, \fBFunctionJumper\&.ReturnCodes\&.NoUnEvent\fP, \fBFunctionJumper\&.ReturnCodes\&.NoDelType\fP, \fBFunctionJumper\&.ReturnCodes\&.CompileError\fP, \fBFunctionJumper\&.ReturnCodes\&.NoTypeForEvent\fP, \fBFunctionJumper\&.ReturnCodes\&.InitFailed\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
All the return codes used by FunctionJumper! 

All the return codes used by FunctionJumper! Getting the same ReturnCode from diffrent functions doesn't meen the same thing\&.\&.\&. 
.PP
Definition in file \fBReturnCodes\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Function Jumper from the source code\&.
