.TH "todo" 3 "Wed Jan 20 2016" "Version V2.0_A12" "Function Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBEventInterface\&.cs\fP \fP" 1c
Omptimize code 
.IP "\fBFile \fBEventMaster\&.cs\fP \fP" 1c
Omptimize code 
.PP
Make this progam NOT classified as a virus 
.PP
Remove need for a C# compiler installed 
.PP
Fix (un?)common stack trace issues 
.PP
Implement Linux suport 
.PP
Implement error handling
.PP

